# export UID=`id -u`; export GID=`id -g`

ubuntu:
  build: .
  dockerfile: Dockerfile.ubuntu
  tty: True
  user: $UID:$GID:$USER

debian:
  build: .
  dockerfile: Dockerfile.debian
  tty: True
  user: $UID:$GID:$USER

dev:
  image: wrf_hydro_gis_preprocessor_debian
  tty: True
  user: $UID:$GID:$USER
  volumes:
    - $REPOSMS/rt_scripts:/source/rt_scripts
    - $HOME/scratch/wrfhydro:/tmp/wrfhydro
